### ISSUE TITLE
streamlink.base broken for HLS/WebTV

### ISSUE THREAD

**Issue by kumarpranay** [Twilight0/repo.twilight0.libs#1]
* Fresh Install Kodi 17.4. 
* Installed the repo.twilight0.libs repository.
* Installed streamlink.proxy package which should give me the streamlink.base and its dependencies
* Wrote a simple plugin to play .m3u8 link using streamlink to resolve the URL.

Debugged and found that:
file: script.module.streamlink.base/resources/lib/streamlink/stream/hls.py
func:  parse_variant_playlist()

The locale variable has been removed from streamlink session and this function assigns it to string "en_US". Then proceeds to call locale.explicit and locale.equivalent. If you comment these everything works.

Have not debugged WebTV yet.

**Comment by Twilight0** [comment]
I am not really using hls library from streamlink as I load m3u8 directly to Kodi's player. Try submitting a PR for your mentioned # comments inside the code.

**Comment by Twilight0** [comment]
Main repo for PRs: https://github.com/Twilight0/script.module.streamlink.base

**Comment by jairoxyz** [comment]
This can be closed
